version: '3.4'

volumes:
  prometheus_data:
  grafana_data:
  rust_data:

services:
  rustserver:
    image: didstopia/rust-server
    volumes:
      - rust_data:/steamcmd/rust
    ports:
      - 28015:28015
      - 28015:28015/udp
      - 28016:28016
      - 28017:8080
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file: ./envs/grafana.env
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 28018:3000
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    expose:
      - 9091
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"